// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ArticleDetails holds parsed and structured content for the In-App reader.
 */
export class ArticleDetails {
    /**
     * Creates a new ArticleDetails instance.
     * @param {Partial<ArticleDetails>} [$$source = {}] - The source object to create the ArticleDetails.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["translatedTitle"] = undefined;
        }
        if (!("heroImage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["heroImage"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("displayDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayDate"] = "";
        }
        if (!("tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tag"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("contentHtml" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentHtml"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["translatedHtml"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArticleDetails instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArticleDetails}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArticleDetails(/** @type {Partial<ArticleDetails>} */($$parsedSource));
    }
}

/**
 * CacheInfo contains statistics about cached files.
 */
export class CacheInfo {
    /**
     * Creates a new CacheInfo instance.
     * @param {Partial<CacheInfo>} [$$source = {}] - The source object to create the CacheInfo.
     */
    constructor($$source = {}) {
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("formatted" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["formatted"] = "";
        }
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CacheInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CacheInfo(/** @type {Partial<CacheInfo>} */($$parsedSource));
    }
}

/**
 * ContentItem represents an installed mod, resourcepack, shaderpack, or datapack.
 */
export class ContentItem {
    /**
     * Creates a new ContentItem instance.
     * @param {Partial<ContentItem>} [$$source = {}] - The source object to create the ContentItem.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "mod" | "resourcepack" | "shaderpack" | "datapack"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modTime"] = 0;
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("authorAvatar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authorAvatar"] = "";
        }
        if (!("iconUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconUrl"] = "";
        }
        if (!("sha1" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha1"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["projectId"] = undefined;
        }
        if (!("hasUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUpdate"] = false;
        }
        if (!("updateVer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updateVer"] = "";
        }
        if (!("updateUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updateUrl"] = "";
        }
        if (!("updateFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updateFile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContentItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContentItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContentItem(/** @type {Partial<ContentItem>} */($$parsedSource));
    }
}

/**
 * JavaUpdateInfo describes a pending Temurin patch update.
 */
export class JavaUpdateInfo {
    /**
     * Creates a new JavaUpdateInfo instance.
     * @param {Partial<JavaUpdateInfo>} [$$source = {}] - The source object to create the JavaUpdateInfo.
     */
    constructor($$source = {}) {
        if (!("major" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["major"] = 0;
        }
        if (!("installedVersion" in $$source)) {
            /**
             * e.g. "17.0.13+11"
             * @member
             * @type {string}
             */
            this["installedVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JavaUpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JavaUpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JavaUpdateInfo(/** @type {Partial<JavaUpdateInfo>} */($$parsedSource));
    }
}

/**
 * LoaderVersionEntry is one selectable modloader version in the UI.
 */
export class LoaderVersionEntry {
    /**
     * Creates a new LoaderVersionEntry instance.
     * @param {Partial<LoaderVersionEntry>} [$$source = {}] - The source object to create the LoaderVersionEntry.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * "", "recommended", "latest"
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoaderVersionEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoaderVersionEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoaderVersionEntry(/** @type {Partial<LoaderVersionEntry>} */($$parsedSource));
    }
}

/**
 * ModItem represents an installed mod in an instance's mods/ directory.
 */
export class ModItem {
    /**
     * Creates a new ModItem instance.
     * @param {Partial<ModItem>} [$$source = {}] - The source object to create the ModItem.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModItem(/** @type {Partial<ModItem>} */($$parsedSource));
    }
}

/**
 * ModVersionChangeInfo contains info and candidate versions for changing a mod's version.
 */
export class ModVersionChangeInfo {
    /**
     * Creates a new ModVersionChangeInfo instance.
     * @param {Partial<ModVersionChangeInfo>} [$$source = {}] - The source object to create the ModVersionChangeInfo.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("modName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modName"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "modrinth" | "curseforge"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("currentSha1" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentSha1"] = "";
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (!("versions" in $$source)) {
            /**
             * @member
             * @type {ModVersionOption[]}
             */
            this["versions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModVersionChangeInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModVersionChangeInfo}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField6_0($$parsedSource["versions"]);
        }
        return new ModVersionChangeInfo(/** @type {Partial<ModVersionChangeInfo>} */($$parsedSource));
    }
}

/**
 * ModVersionOption represents a version choice for switching versions of an installed mod.
 */
export class ModVersionOption {
    /**
     * Creates a new ModVersionOption instance.
     * @param {Partial<ModVersionOption>} [$$source = {}] - The source object to create the ModVersionOption.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("versionNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionNumber"] = "";
        }
        if (!("gameVersions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["gameVersions"] = [];
        }
        if (!("loaders" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["loaders"] = [];
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (!("datePublished" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["datePublished"] = "";
        }
        if (!("isCurrent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCurrent"] = false;
        }
        if (!("versionType" in $$source)) {
            /**
             * "release" | "beta" | "alpha"
             * @member
             * @type {string}
             */
            this["versionType"] = "";
        }
        if (!("changelog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["changelog"] = "";
        }
        if (!("isCompatible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCompatible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModVersionOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModVersionOption}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("gameVersions" in $$parsedSource) {
            $$parsedSource["gameVersions"] = $$createField3_0($$parsedSource["gameVersions"]);
        }
        if ("loaders" in $$parsedSource) {
            $$parsedSource["loaders"] = $$createField4_0($$parsedSource["loaders"]);
        }
        return new ModVersionOption(/** @type {Partial<ModVersionOption>} */($$parsedSource));
    }
}

/**
 * ModpackDetails contains full info and versions for a modpack.
 */
export class ModpackDetails {
    /**
     * Creates a new ModpackDetails instance.
     * @param {Partial<ModpackDetails>} [$$source = {}] - The source object to create the ModpackDetails.
     */
    constructor($$source = {}) {
        if (!("item" in $$source)) {
            /**
             * @member
             * @type {ModpackItem}
             */
            this["item"] = (new ModpackItem());
        }
        if (!("versions" in $$source)) {
            /**
             * @member
             * @type {ModpackVersionItem[]}
             */
            this["versions"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("webUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["webUrl"] = "";
        }
        if (!("gallery" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["gallery"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModpackDetails instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModpackDetails}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField0_0($$parsedSource["item"]);
        }
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField1_0($$parsedSource["versions"]);
        }
        if ("gallery" in $$parsedSource) {
            $$parsedSource["gallery"] = $$createField4_0($$parsedSource["gallery"]);
        }
        return new ModpackDetails(/** @type {Partial<ModpackDetails>} */($$parsedSource));
    }
}

/**
 * ModpackItem is a unified representation of a modpack from Modrinth, CurseForge or FTB.
 */
export class ModpackItem {
    /**
     * Creates a new ModpackItem instance.
     * @param {Partial<ModpackItem>} [$$source = {}] - The source object to create the ModpackItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "modrinth" | "curseforge" | "ftb"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("icon_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon_url"] = "";
        }
        if (!("banner_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["banner_url"] = "";
        }
        if (!("downloads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloads"] = 0;
        }
        if (!("follows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["follows"] = 0;
        }
        if (!("categories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["categories"] = [];
        }
        if (!("game_versions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["game_versions"] = [];
        }
        if (!("loaders" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["loaders"] = [];
        }
        if (!("date_modified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date_modified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModpackItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModpackItem}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField10_0($$parsedSource["categories"]);
        }
        if ("game_versions" in $$parsedSource) {
            $$parsedSource["game_versions"] = $$createField11_0($$parsedSource["game_versions"]);
        }
        if ("loaders" in $$parsedSource) {
            $$parsedSource["loaders"] = $$createField12_0($$parsedSource["loaders"]);
        }
        return new ModpackItem(/** @type {Partial<ModpackItem>} */($$parsedSource));
    }
}

/**
 * ModpackVersionItem represents a downloadable release version of a modpack.
 */
export class ModpackVersionItem {
    /**
     * Creates a new ModpackVersionItem instance.
     * @param {Partial<ModpackVersionItem>} [$$source = {}] - The source object to create the ModpackVersionItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version_number" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version_number"] = "";
        }
        if (!("game_versions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["game_versions"] = [];
        }
        if (!("loaders" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["loaders"] = [];
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("file_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_name"] = "";
        }
        if (!("file_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["file_size"] = 0;
        }
        if (!("date_published" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date_published"] = "";
        }
        if (!("changelog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["changelog"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModpackVersionItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModpackVersionItem}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("game_versions" in $$parsedSource) {
            $$parsedSource["game_versions"] = $$createField3_0($$parsedSource["game_versions"]);
        }
        if ("loaders" in $$parsedSource) {
            $$parsedSource["loaders"] = $$createField4_0($$parsedSource["loaders"]);
        }
        return new ModpackVersionItem(/** @type {Partial<ModpackVersionItem>} */($$parsedSource));
    }
}

/**
 * ModrinthHit represents a mod search result from Modrinth API.
 */
export class ModrinthHit {
    /**
     * Creates a new ModrinthHit instance.
     * @param {Partial<ModrinthHit>} [$$source = {}] - The source object to create the ModrinthHit.
     */
    constructor($$source = {}) {
        if (!("project_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_id"] = "";
        }
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("categories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["categories"] = [];
        }
        if (!("client_side" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_side"] = "";
        }
        if (!("server_side" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_side"] = "";
        }
        if (!("icon_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon_url"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("downloads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloads"] = 0;
        }
        if (!("follows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["follows"] = 0;
        }
        if (!("versions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["versions"] = [];
        }
        if (!("gallery" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["gallery"] = [];
        }
        if (!("date_modified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date_modified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModrinthHit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModrinthHit}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField4_0($$parsedSource["categories"]);
        }
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField11_0($$parsedSource["versions"]);
        }
        if ("gallery" in $$parsedSource) {
            $$parsedSource["gallery"] = $$createField12_0($$parsedSource["gallery"]);
        }
        return new ModrinthHit(/** @type {Partial<ModrinthHit>} */($$parsedSource));
    }
}

/**
 * ModrinthSearchResponse is the response structure of Modrinth search endpoint.
 */
export class ModrinthSearchResponse {
    /**
     * Creates a new ModrinthSearchResponse instance.
     * @param {Partial<ModrinthSearchResponse>} [$$source = {}] - The source object to create the ModrinthSearchResponse.
     */
    constructor($$source = {}) {
        if (!("hits" in $$source)) {
            /**
             * @member
             * @type {ModrinthHit[]}
             */
            this["hits"] = [];
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("total_hits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_hits"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModrinthSearchResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModrinthSearchResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField0_0($$parsedSource["hits"]);
        }
        return new ModrinthSearchResponse(/** @type {Partial<ModrinthSearchResponse>} */($$parsedSource));
    }
}

/**
 * NewsEntry is one article card for the UI.
 */
export class NewsEntry {
    /**
     * Creates a new NewsEntry instance.
     * @param {Partial<NewsEntry>} [$$source = {}] - The source object to create the NewsEntry.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tag"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * css class: "" | "event" | "patch"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("displayDate" in $$source)) {
            /**
             * "2 января 2026"
             * @member
             * @type {string}
             */
            this["displayDate"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["image"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewsEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NewsEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewsEntry(/** @type {Partial<NewsEntry>} */($$parsedSource));
    }
}

/**
 * ResolvedDependency represents a resolved dependency ready for installation.
 */
export class ResolvedDependency {
    /**
     * Creates a new ResolvedDependency instance.
     * @param {Partial<ResolvedDependency>} [$$source = {}] - The source object to create the ResolvedDependency.
     */
    constructor($$source = {}) {
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (!("projectSlug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectSlug"] = "";
        }
        if (!("projectTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectTitle"] = "";
        }
        if (!("iconUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconUrl"] = "";
        }
        if (!("dependencyType" in $$source)) {
            /**
             * "required" | "optional"
             * @member
             * @type {string}
             */
            this["dependencyType"] = "";
        }
        if (!("versionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionId"] = "";
        }
        if (!("versionNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionNumber"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("alreadyInstalled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alreadyInstalled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedDependency instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvedDependency}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvedDependency(/** @type {Partial<ResolvedDependency>} */($$parsedSource));
    }
}

/**
 * WorldItem represents a Minecraft world save in saves/.
 */
export class WorldItem {
    /**
     * Creates a new WorldItem instance.
     * @param {Partial<WorldItem>} [$$source = {}] - The source object to create the WorldItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("folderName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderName"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("lastPlayed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastPlayed"] = 0;
        }
        if (!("iconBase64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorldItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorldItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorldItem(/** @type {Partial<WorldItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ModVersionOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = ModpackItem.createFrom;
const $$createType4 = ModpackVersionItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ModrinthHit.createFrom;
const $$createType7 = $Create.Array($$createType6);
