// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails-bound backend service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcher$0 from "./internal/launcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "./internal/launcher/auth/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddOfflineAccount creates and selects a new offline account.
 * @param {string} username
 * @returns {$CancellablePromise<auth$0.Account | null>}
 */
export function AddOfflineAccount(username) {
    return $Call.ByID(2021143582, username).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CancelInstallModpack aborts an ongoing modpack installation.
 * @returns {$CancellablePromise<void>}
 */
export function CancelInstallModpack() {
    return $Call.ByID(2004683935);
}

/**
 * CancelMicrosoftAuth aborts any pending Microsoft device auth polling.
 * @returns {$CancellablePromise<void>}
 */
export function CancelMicrosoftAuth() {
    return $Call.ByID(952624387);
}

/**
 * CancelPlay aborts an in-progress download/install or stops a running game.
 * @returns {$CancellablePromise<void>}
 */
export function CancelPlay() {
    return $Call.ByID(2027942073);
}

/**
 * ChangeModVersion installs a new version of a mod and deletes the old one.
 * @param {string} instanceID
 * @param {string} oldFilename
 * @param {string} downloadURL
 * @param {string} newFilename
 * @param {string} source
 * @param {string} projectID
 * @returns {$CancellablePromise<launcher$0.ContentItem | null>}
 */
export function ChangeModVersion(instanceID, oldFilename, downloadURL, newFilename, source, projectID) {
    return $Call.ByID(1014079101, instanceID, oldFilename, downloadURL, newFilename, source, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckCurseForgeDependencies checks if the CurseForge mod has any missing dependencies.
 * @param {string} instanceID
 * @param {string} modIDStr
 * @returns {$CancellablePromise<launcher$0.ResolvedDependency[]>}
 */
export function CheckCurseForgeDependencies(instanceID, modIDStr) {
    return $Call.ByID(2295831459, instanceID, modIDStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CheckInstanceModUpdates checks for mod updates via Modrinth.
 * @param {string} id
 * @returns {$CancellablePromise<{ [_ in string]?: launcher$0.ContentItem }>}
 */
export function CheckInstanceModUpdates(id) {
    return $Call.ByID(1074664662, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * CheckInstanceModpackUpdate checks if there is a newer version of the upstream modpack.
 * @param {string} instanceID
 * @returns {$CancellablePromise<$models.ModpackUpdateInfo | null>}
 */
export function CheckInstanceModpackUpdate(instanceID) {
    return $Call.ByID(3696403472, instanceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * CheckJavaUpdates checks managed Temurin installs against the latest Adoptium releases.
 * @returns {$CancellablePromise<launcher$0.JavaUpdateInfo[]>}
 */
export function CheckJavaUpdates() {
    return $Call.ByID(1281039863).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * CheckLauncherUpdate queries GitHub for the latest release and compares it
 * with the running launcher version.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckLauncherUpdate() {
    return $Call.ByID(2902729478).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * CheckModDependencies checks if the mod has any missing required or optional dependencies.
 * @param {string} instanceID
 * @param {string} projectIDOrSlug
 * @returns {$CancellablePromise<launcher$0.ResolvedDependency[]>}
 */
export function CheckModDependencies(instanceID, projectIDOrSlug) {
    return $Call.ByID(3109439320, instanceID, projectIDOrSlug).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClearAccountCape removes/hides the cape from the given account.
 * @param {string} accountID
 * @returns {$CancellablePromise<auth$0.Account | null>}
 */
export function ClearAccountCape(accountID) {
    return $Call.ByID(3126784570, accountID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearCache completely clears the cache directory and returns the freed space info.
 * @returns {$CancellablePromise<launcher$0.CacheInfo | null>}
 */
export function ClearCache() {
    return $Call.ByID(1413834504).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * CloneInstance duplicates a build, copying its game folder to a new instance.
 * @param {string} instanceID
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function CloneInstance(instanceID) {
    return $Call.ByID(255678837, instanceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * CreateGroup creates a new custom folder / group if it doesn't already exist.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateGroup(name) {
    return $Call.ByID(3452783212, name);
}

/**
 * CreateInstance adds a new build with its own folder and selects it.
 * For modloader builds loaderVersion may be empty — the recommended or
 * newest version is picked automatically.
 * @param {string} name
 * @param {string} versionID
 * @param {string} loader
 * @param {string} loaderVersion
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function CreateInstance(name, versionID, loader, loaderVersion) {
    return $Call.ByID(3775172082, name, versionID, loader, loaderVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * DeleteGroup removes a group and unassigns instances belonging to it.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(name) {
    return $Call.ByID(3779215765, name);
}

/**
 * DeleteInstance removes a build and its folder, returning the id of the
 * build that becomes active afterwards ("" if none left).
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function DeleteInstance(id) {
    return $Call.ByID(472983421, id);
}

/**
 * DeleteInstanceContent removes a file from instance folder.
 * @param {string} instanceID
 * @param {string} itemType
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function DeleteInstanceContent(instanceID, itemType, filename) {
    return $Call.ByID(2292533882, instanceID, itemType, filename);
}

/**
 * DeleteInstanceScreenshot removes a screenshot.
 * @param {string} instanceID
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function DeleteInstanceScreenshot(instanceID, filename) {
    return $Call.ByID(4152503097, instanceID, filename);
}

/**
 * DeleteInstanceWorld deletes a world directory in saves/.
 * @param {string} instanceID
 * @param {string} folderName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteInstanceWorld(instanceID, folderName) {
    return $Call.ByID(2683589083, instanceID, folderName);
}

/**
 * DeleteMod deletes a mod jar file from the instance.
 * @param {string} instanceID
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMod(instanceID, filename) {
    return $Call.ByID(4063556150, instanceID, filename);
}

/**
 * DetectInstalledLaunchers scans default locations for popular Minecraft launchers.
 * @returns {$CancellablePromise<$models.DetectedLauncher[]>}
 */
export function DetectInstalledLaunchers() {
    return $Call.ByID(385058761).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * DownloadLauncherUpdate downloads the latest release binary in the background,
 * replaces the running executable and restarts the launcher.
 * Progress is reported via "update-progress" events; completion via
 * "update-done" and failures via "update-error".
 * @returns {$CancellablePromise<void>}
 */
export function DownloadLauncherUpdate() {
    return $Call.ByID(1801846380);
}

/**
 * ExportInstance packages the instance into an archive (.mrpack or .zip).
 * @param {string} instanceID
 * @returns {$CancellablePromise<string>}
 */
export function ExportInstance(instanceID) {
    return $Call.ByID(1979883944, instanceID);
}

/**
 * FetchTextureBase64 fetches an image from URL and returns a data:image/png;base64 string.
 * @param {string} url
 * @returns {$CancellablePromise<string>}
 */
export function FetchTextureBase64(url) {
    return $Call.ByID(3299522565, url);
}

/**
 * GetAccounts returns all configured accounts and active ID.
 * @returns {$CancellablePromise<auth$0.AccountsData>}
 */
export function GetAccounts() {
    return $Call.ByID(3988648011).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetArticle fetches and parses the full content of a minecraft.net article.
 * @param {string} url
 * @returns {$CancellablePromise<launcher$0.ArticleDetails | null>}
 */
export function GetArticle(url) {
    return $Call.ByID(1901880863, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetCacheInfo returns statistics about the cached files.
 * @returns {$CancellablePromise<launcher$0.CacheInfo | null>}
 */
export function GetCacheInfo() {
    return $Call.ByID(1735807799).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetInstalledMods returns a list of installed mods in the instance's mods folder.
 * @param {string} id
 * @returns {$CancellablePromise<launcher$0.ModItem[]>}
 */
export function GetInstalledMods(id) {
    return $Call.ByID(3171754194, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetInstanceAllContent retrieves all mods, resourcepacks, shaderpacks, and datapacks.
 * @param {string} id
 * @returns {$CancellablePromise<launcher$0.ContentItem[]>}
 */
export function GetInstanceAllContent(id) {
    return $Call.ByID(3253895392, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetInstanceCrashReports returns crash reports for the instance.
 * @param {string} instanceID
 * @returns {$CancellablePromise<$models.CrashReport[]>}
 */
export function GetInstanceCrashReports(instanceID) {
    return $Call.ByID(4023737422, instanceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * GetInstanceLogs reads the latest log of the instance.
 * @param {string} instanceID
 * @returns {$CancellablePromise<string>}
 */
export function GetInstanceLogs(instanceID) {
    return $Call.ByID(1688436071, instanceID);
}

/**
 * GetInstanceScreenshots scans the instance's screenshots directory.
 * @param {string} instanceID
 * @returns {$CancellablePromise<$models.ScreenshotItem[]>}
 */
export function GetInstanceScreenshots(instanceID) {
    return $Call.ByID(2267059649, instanceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetInstanceWorlds returns saved worlds for an instance.
 * @param {string} id
 * @returns {$CancellablePromise<launcher$0.WorldItem[]>}
 */
export function GetInstanceWorlds(id) {
    return $Call.ByID(1625850609, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * GetInstances returns all created builds.
 * @returns {$CancellablePromise<$models.Instance[]>}
 */
export function GetInstances() {
    return $Call.ByID(2770610989).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetJavaRuntimesStatus checks availability for Java 8, 17, and 21.
 * @returns {$CancellablePromise<$models.JavaRuntimeStatus[]>}
 */
export function GetJavaRuntimesStatus() {
    return $Call.ByID(253493576).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetLauncherLogs returns recent content of launcher.log.
 * @returns {$CancellablePromise<string>}
 */
export function GetLauncherLogs() {
    return $Call.ByID(2635380860);
}

/**
 * GetLoaderVersions exposes the modloader version lists to the UI.
 * @param {string} loader
 * @param {string} mcVersion
 * @returns {$CancellablePromise<launcher$0.LoaderVersionEntry[]>}
 */
export function GetLoaderVersions(loader, mcVersion) {
    return $Call.ByID(2502109817, loader, mcVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GetModAvailableVersions returns available versions for an installed mod from Modrinth/CurseForge.
 * @param {string} instanceID
 * @param {string} filename
 * @returns {$CancellablePromise<launcher$0.ModVersionChangeInfo | null>}
 */
export function GetModAvailableVersions(instanceID, filename) {
    return $Call.ByID(3166820093, instanceID, filename).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * GetModpackDetails fetches full details, description, and versions for a modpack.
 * @param {string} source
 * @param {string} idOrSlug
 * @returns {$CancellablePromise<launcher$0.ModpackDetails | null>}
 */
export function GetModpackDetails(source, idOrSlug) {
    return $Call.ByID(2602071822, source, idOrSlug).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * GetNews returns the official Minecraft launcher news (cached).
 * @returns {$CancellablePromise<launcher$0.NewsEntry[]>}
 */
export function GetNews() {
    return $Call.ByID(3569506164).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * GetPresetCapes returns curated list of preset capes with base64 DataURLs preloaded.
 * @returns {$CancellablePromise<auth$0.PresetCape[]>}
 */
export function GetPresetCapes() {
    return $Call.ByID(790286292).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * GetSettings returns the current settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * GetState returns settings + version list (cached manifest, offline-friendly) + accounts.
 * @returns {$CancellablePromise<$models.StatePayload>}
 */
export function GetState() {
    return $Call.ByID(2490316256).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * ImportInstanceDialog opens file dialog to pick an instance archive to import.
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function ImportInstanceDialog() {
    return $Call.ByID(2145452531).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ImportInstanceFile imports a modpack from a local file path (e.g. from dialog or drag-and-drop).
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function ImportInstanceFile(filePath) {
    return $Call.ByID(495833321, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ImportSelectedInstances imports one or multiple detected instance directories into WaiLauncher with progress.
 * @param {string[]} instPaths
 * @returns {$CancellablePromise<($models.Instance | null)[]>}
 */
export function ImportSelectedInstances(instPaths) {
    return $Call.ByID(773482003, instPaths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * InstallCurseForgeMod installs the latest compatible project version from CurseForge directly into the instance.
 * @param {string} instanceID
 * @param {string} modIDStr
 * @param {string} projectType
 * @returns {$CancellablePromise<launcher$0.ModItem | null>}
 */
export function InstallCurseForgeMod(instanceID, modIDStr, projectType) {
    return $Call.ByID(2977243755, instanceID, modIDStr, projectType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * InstallCurseForgeModWithDependencies installs a CurseForge mod and its dependencies.
 * @param {string} instanceID
 * @param {string} modIDStr
 * @param {string} projectType
 * @param {string[]} depDownloadUrls
 * @returns {$CancellablePromise<launcher$0.ModItem | null>}
 */
export function InstallCurseForgeModWithDependencies(instanceID, modIDStr, projectType, depDownloadUrls) {
    return $Call.ByID(917302718, instanceID, modIDStr, projectType, depDownloadUrls).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * InstallJavaRuntime triggers 1-click download of Adoptium OpenJDK for the specified major version.
 * @param {number} major
 * @returns {$CancellablePromise<void>}
 */
export function InstallJavaRuntime(major) {
    return $Call.ByID(1150724860, major);
}

/**
 * InstallModWithDependencies installs a main mod and any selected dependency URLs into the instance's mods folder.
 * @param {string} instanceID
 * @param {string} projectIDOrSlug
 * @param {string} projectType
 * @param {string[]} depDownloadUrls
 * @returns {$CancellablePromise<launcher$0.ModItem | null>}
 */
export function InstallModWithDependencies(instanceID, projectIDOrSlug, projectType, depDownloadUrls) {
    return $Call.ByID(965410577, instanceID, projectIDOrSlug, projectType, depDownloadUrls).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * InstallModpack downloads and installs a modpack from Modrinth, CurseForge or FTB.
 * @param {string} source
 * @param {string} downloadURL
 * @param {string} customName
 * @param {string} packID
 * @param {string} versionID
 * @param {string} versionName
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function InstallModpack(source, downloadURL, customName, packID, versionID, versionName) {
    return $Call.ByID(2021981629, source, downloadURL, customName, packID, versionID, versionName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * InstallModrinthMod installs the latest compatible project version from Modrinth directly into the instance.
 * @param {string} instanceID
 * @param {string} projectIDOrSlug
 * @param {string} projectType
 * @returns {$CancellablePromise<launcher$0.ModItem | null>}
 */
export function InstallModrinthMod(instanceID, projectIDOrSlug, projectType) {
    return $Call.ByID(308661631, instanceID, projectIDOrSlug, projectType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * OpenDataDir opens the launcher data directory in Windows Explorer / system file manager.
 * @returns {$CancellablePromise<void>}
 */
export function OpenDataDir() {
    return $Call.ByID(3225130928);
}

/**
 * OpenInstanceDir opens the instance folder in Explorer.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenInstanceDir(id) {
    return $Call.ByID(703317221, id);
}

/**
 * OpenInstanceSubFolder opens a specific subfolder (e.g. "mods", "saves", "resourcepacks", "shaderpacks") in Explorer.
 * @param {string} instanceID
 * @param {string} subFolder
 * @returns {$CancellablePromise<void>}
 */
export function OpenInstanceSubFolder(instanceID, subFolder) {
    return $Call.ByID(3047866504, instanceID, subFolder);
}

/**
 * OpenLogsFolder opens the directory containing launcher.log in Windows File Explorer.
 * @returns {$CancellablePromise<void>}
 */
export function OpenLogsFolder() {
    return $Call.ByID(313822178);
}

/**
 * OpenScreenshotsFolder opens Windows Explorer inside instance's screenshots folder.
 * @param {string} instanceID
 * @returns {$CancellablePromise<void>}
 */
export function OpenScreenshotsFolder(instanceID) {
    return $Call.ByID(1106169050, instanceID);
}

/**
 * OpenURL opens a link in the system browser.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(3584934946, url);
}

/**
 * PickCapeFile opens a dialog to select a cape PNG file.
 * @returns {$CancellablePromise<$models.FilePickResult | null>}
 */
export function PickCapeFile() {
    return $Call.ByID(2285862953).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * PickDataDir shows a directory picker dialog to select the data folder.
 * @returns {$CancellablePromise<string>}
 */
export function PickDataDir() {
    return $Call.ByID(1428376223);
}

/**
 * PickInstanceIcon opens a file dialog to choose an icon for an instance.
 * @param {string} instanceID
 * @returns {$CancellablePromise<string>}
 */
export function PickInstanceIcon(instanceID) {
    return $Call.ByID(3843401290, instanceID);
}

/**
 * PickJavaPath shows a file dialog to select the java executable.
 * @returns {$CancellablePromise<string>}
 */
export function PickJavaPath() {
    return $Call.ByID(693028711);
}

/**
 * PickLauncherFolder opens directory picker for custom launcher path.
 * @returns {$CancellablePromise<string>}
 */
export function PickLauncherFolder() {
    return $Call.ByID(2326912660);
}

/**
 * PickSkinFile opens a dialog to select a skin PNG file.
 * @returns {$CancellablePromise<$models.FilePickResult | null>}
 */
export function PickSkinFile() {
    return $Call.ByID(1238116047).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * Play starts the install+launch pipeline for a build (instance)
 * asynchronously. Progress is delivered via the "launch" event.
 * @param {string} instanceID
 * @returns {$CancellablePromise<void>}
 */
export function Play(instanceID) {
    return $Call.ByID(4166957835, instanceID);
}

/**
 * PollMicrosoftAuth waits for the user to complete login in the browser.
 * @param {string} deviceCode
 * @param {number} interval
 * @returns {$CancellablePromise<auth$0.Account | null>}
 */
export function PollMicrosoftAuth(deviceCode, interval) {
    return $Call.ByID(1904858970, deviceCode, interval).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RefreshAccount refreshes account profile / tokens.
 * @param {string} id
 * @returns {$CancellablePromise<auth$0.Account | null>}
 */
export function RefreshAccount(id) {
    return $Call.ByID(3683453299, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RefreshVersions force-fetches the manifest from Mojang.
 * @returns {$CancellablePromise<$models.StatePayload>}
 */
export function RefreshVersions() {
    return $Call.ByID(483914745).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * RemoveAccount deletes an account by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAccount(id) {
    return $Call.ByID(205763644, id);
}

/**
 * RenameGroup renames a group and updates all instances belonging to it.
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameGroup(oldName, newName) {
    return $Call.ByID(3980666162, oldName, newName);
}

/**
 * ReorderInstances updates the sort order of instances based on the ordered list of IDs.
 * @param {string[]} orderedIDs
 * @returns {$CancellablePromise<void>}
 */
export function ReorderInstances(orderedIDs) {
    return $Call.ByID(3294578664, orderedIDs);
}

/**
 * SaveSettings validates and persists settings.
 * @param {$models.Settings} s
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(s) {
    return $Call.ByID(1949631069, s);
}

/**
 * ScanCustomLauncherDir scans a user-selected folder for instances.
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.DetectedLauncher>}
 */
export function ScanCustomLauncherDir(dirPath) {
    return $Call.ByID(1001562914, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * SearchCurseForgeMods searches for projects (mods, resourcepacks, shaders) on CurseForge API.
 * @param {string} query
 * @param {string} projectType
 * @param {string} loader
 * @param {string} mcVersion
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<launcher$0.ModrinthSearchResponse | null>}
 */
export function SearchCurseForgeMods(query, projectType, loader, mcVersion, offset, limit) {
    return $Call.ByID(695745705, query, projectType, loader, mcVersion, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * SearchModpacks queries Modrinth or CurseForge for modpacks.
 * @param {string} source
 * @param {string} query
 * @param {string} mcVersion
 * @param {string} loader
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<launcher$0.ModpackItem[]>}
 */
export function SearchModpacks(source, query, mcVersion, loader, offset, limit) {
    return $Call.ByID(4154090043, source, query, mcVersion, loader, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * SearchModrinthMods searches for projects (mods, resourcepacks, shaders) on Modrinth API.
 * @param {string} query
 * @param {string} projectType
 * @param {string} loader
 * @param {string} mcVersion
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<launcher$0.ModrinthSearchResponse | null>}
 */
export function SearchModrinthMods(query, projectType, loader, mcVersion, offset, limit) {
    return $Call.ByID(4019887605, query, projectType, loader, mcVersion, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * SelectAccount changes the active account.
 * @param {string} id
 * @returns {$CancellablePromise<auth$0.Account | null>}
 */
export function SelectAccount(id) {
    return $Call.ByID(889985564, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetAccountCape updates or activates a cape for the given account.
 * @param {string} accountID
 * @param {string} capeURLOrDataURL
 * @param {string} capeID
 * @returns {$CancellablePromise<auth$0.Account | null>}
 */
export function SetAccountCape(accountID, capeURLOrDataURL, capeID) {
    return $Call.ByID(1386321897, accountID, capeURLOrDataURL, capeID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetAccountSkin updates the skin for the given account.
 * @param {string} accountID
 * @param {string} filePathOrDataURL
 * @param {string} variant
 * @returns {$CancellablePromise<auth$0.Account | null>}
 */
export function SetAccountSkin(accountID, filePathOrDataURL, variant) {
    return $Call.ByID(4246159227, accountID, filePathOrDataURL, variant).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetActiveInstance selects the build the ИГРАТЬ button launches.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveInstance(id) {
    return $Call.ByID(3689603138, id);
}

/**
 * ShowFileInExplorer opens Windows Explorer with the specific file selected.
 * @param {string} instanceID
 * @param {string} itemType
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function ShowFileInExplorer(instanceID, itemType, filename) {
    return $Call.ByID(2304076882, instanceID, itemType, filename);
}

/**
 * StartMicrosoftAuth initiates the Microsoft OAuth device code flow.
 * @returns {$CancellablePromise<auth$0.DeviceCodeResponse | null>}
 */
export function StartMicrosoftAuth() {
    return $Call.ByID(2238697207).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType54($result);
    }));
}

/**
 * StopGame terminates a running Minecraft instance or cancels an in-progress launch.
 * @returns {$CancellablePromise<void>}
 */
export function StopGame() {
    return $Call.ByID(1920645615);
}

/**
 * ToggleInstanceContent toggles enabled/disabled state of a content item.
 * @param {string} instanceID
 * @param {string} itemType
 * @param {string} filename
 * @param {boolean} enable
 * @returns {$CancellablePromise<void>}
 */
export function ToggleInstanceContent(instanceID, itemType, filename, enable) {
    return $Call.ByID(3456782275, instanceID, itemType, filename, enable);
}

/**
 * ToggleMod enables or disables a mod by renaming .jar <-> .jar.disabled.
 * @param {string} instanceID
 * @param {string} filename
 * @param {boolean} enable
 * @returns {$CancellablePromise<void>}
 */
export function ToggleMod(instanceID, filename, enable) {
    return $Call.ByID(884167387, instanceID, filename, enable);
}

/**
 * TranslateArticle translates the article content to the specified language (e.g. "ru").
 * @param {string} url
 * @param {string} lang
 * @returns {$CancellablePromise<launcher$0.ArticleDetails | null>}
 */
export function TranslateArticle(url, lang) {
    return $Call.ByID(4023605041, url, lang).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * UninstallJavaRuntime removes the managed Adoptium OpenJDK for the specified major version.
 * @param {number} major
 * @returns {$CancellablePromise<void>}
 */
export function UninstallJavaRuntime(major) {
    return $Call.ByID(1644072527, major);
}

/**
 * UpdateInstanceGroup updates the folder/category name of an instance.
 * @param {string} instanceID
 * @param {string} group
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function UpdateInstanceGroup(instanceID, group) {
    return $Call.ByID(3514988462, instanceID, group).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * UpdateInstanceLaunchConfig persists per-instance launch overrides.
 * @param {string} instanceID
 * @param {number} ramMB
 * @param {string} javaPath
 * @param {string} jvmArgs
 * @param {string} jvmPreset
 * @param {boolean} useCustomWindow
 * @param {boolean} fullscreen
 * @param {number} winW
 * @param {number} winH
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function UpdateInstanceLaunchConfig(instanceID, ramMB, javaPath, jvmArgs, jvmPreset, useCustomWindow, fullscreen, winW, winH) {
    return $Call.ByID(2722393462, instanceID, ramMB, javaPath, jvmArgs, jvmPreset, useCustomWindow, fullscreen, winW, winH).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * UpdateInstanceMod downloads the new version of a mod and removes the old jar.
 * @param {string} instanceID
 * @param {string} oldFilename
 * @param {string} newURL
 * @param {string} newFilename
 * @returns {$CancellablePromise<void>}
 */
export function UpdateInstanceMod(instanceID, oldFilename, newURL, newFilename) {
    return $Call.ByID(2991311845, instanceID, oldFilename, newURL, newFilename);
}

/**
 * UpdateInstanceModpack updates an existing instance to a newer version of the modpack, preserving saves and settings.
 * @param {string} instanceID
 * @param {string} newDownloadURL
 * @param {string} newVersionID
 * @param {string} newVersionName
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function UpdateInstanceModpack(instanceID, newDownloadURL, newVersionID, newVersionName) {
    return $Call.ByID(2460410624, instanceID, newDownloadURL, newVersionID, newVersionName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * UpdateInstanceSettings updates name, server address, version, loader, and loader version.
 * @param {string} instanceID
 * @param {string} name
 * @param {string} serverAddress
 * @param {string} versionID
 * @param {string} loader
 * @param {string} loaderVersion
 * @param {string} group
 * @returns {$CancellablePromise<$models.Instance | null>}
 */
export function UpdateInstanceSettings(instanceID, name, serverAddress, versionID, loader, loaderVersion, group) {
    return $Call.ByID(4197567994, instanceID, name, serverAddress, versionID, loader, loaderVersion, group).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * VerifyInstanceFiles forcibly checks SHA1 and sizes of client jar, libraries, and assets for an instance.
 * @param {string} instanceID
 * @returns {$CancellablePromise<$models.VerifyResult>}
 */
export function VerifyInstanceFiles(instanceID) {
    return $Call.ByID(2454824462, instanceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WindowClose() {
    return $Call.ByID(1474073651);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WindowMinimize() {
    return $Call.ByID(1846147565);
}

/**
 * WindowToggleMaximize toggles maximization and returns the new state.
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowToggleMaximize() {
    return $Call.ByID(3361853791);
}

// Private type creation functions
const $$createType0 = auth$0.Account.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = launcher$0.ContentItem.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = launcher$0.ResolvedDependency.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType2);
const $$createType7 = $models.ModpackUpdateInfo.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = launcher$0.JavaUpdateInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.UpdateInfo.createFrom;
const $$createType12 = launcher$0.CacheInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.Instance.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.DetectedLauncher.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = auth$0.AccountsData.createFrom;
const $$createType19 = launcher$0.ArticleDetails.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = launcher$0.ModItem.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($$createType2);
const $$createType24 = $models.CrashReport.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = $models.ScreenshotItem.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = launcher$0.WorldItem.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $Create.Array($$createType14);
const $$createType31 = $models.JavaRuntimeStatus.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = launcher$0.LoaderVersionEntry.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = launcher$0.ModVersionChangeInfo.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = launcher$0.ModpackDetails.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
const $$createType39 = launcher$0.NewsEntry.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = auth$0.PresetCape.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = $models.Settings.createFrom;
const $$createType44 = $models.StatePayload.createFrom;
const $$createType45 = $Create.Array($$createType15);
const $$createType46 = $Create.Nullable($$createType21);
const $$createType47 = $models.FilePickResult.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = launcher$0.ModrinthSearchResponse.createFrom;
const $$createType50 = $Create.Nullable($$createType49);
const $$createType51 = launcher$0.ModpackItem.createFrom;
const $$createType52 = $Create.Array($$createType51);
const $$createType53 = auth$0.DeviceCodeResponse.createFrom;
const $$createType54 = $Create.Nullable($$createType53);
const $$createType55 = $models.VerifyResult.createFrom;
