// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "./internal/launcher/auth/models.js";

/**
 * CrashReport is one entry from the crash-reports/ folder.
 */
export class CrashReport {
    /**
     * Creates a new CrashReport instance.
     * @param {Partial<CrashReport>} [$$source = {}] - The source object to create the CrashReport.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modTime"] = 0;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("summary" in $$source)) {
            /**
             * first meaningful error line
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * full text (bounded)
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrashReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CrashReport}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CrashReport(/** @type {Partial<CrashReport>} */($$parsedSource));
    }
}

export class DetectedInstance {
    /**
     * Creates a new DetectedInstance instance.
     * @param {Partial<DetectedInstance>} [$$source = {}] - The source object to create the DetectedInstance.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("versionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionId"] = "";
        }
        if (!("loader" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["loader"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["loaderVersion"] = undefined;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modpackSource"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modpackId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modpackVersionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modpackVersionName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedInstance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectedInstance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectedInstance(/** @type {Partial<DetectedInstance>} */($$parsedSource));
    }
}

export class DetectedLauncher {
    /**
     * Creates a new DetectedLauncher instance.
     * @param {Partial<DetectedLauncher>} [$$source = {}] - The source object to create the DetectedLauncher.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("basePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["basePath"] = "";
        }
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (!("instances" in $$source)) {
            /**
             * @member
             * @type {DetectedInstance[]}
             */
            this["instances"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedLauncher instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectedLauncher}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("instances" in $$parsedSource) {
            $$parsedSource["instances"] = $$createField4_0($$parsedSource["instances"]);
        }
        return new DetectedLauncher(/** @type {Partial<DetectedLauncher>} */($$parsedSource));
    }
}

/**
 * FilePickResult holds local file path and base64 data URL from file dialog.
 */
export class FilePickResult {
    /**
     * Creates a new FilePickResult instance.
     * @param {Partial<FilePickResult>} [$$source = {}] - The source object to create the FilePickResult.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("dataUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataUrl"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilePickResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FilePickResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilePickResult(/** @type {Partial<FilePickResult>} */($$parsedSource));
    }
}

/**
 * Instance is one user-created build ("сборка"): a version + modloader combo
 * with its own game folder, like Modrinth App profiles.
 */
export class Instance {
    /**
     * Creates a new Instance instance.
     * @param {Partial<Instance>} [$$source = {}] - The source object to create the Instance.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("versionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionId"] = "";
        }
        if (!("loader" in $$source)) {
            /**
             * vanilla | fabric | forge | neoforge
             * @member
             * @type {string}
             */
            this["loader"] = "";
        }
        if (!("loaderVersion" in $$source)) {
            /**
             * e.g. 47.2.20; "" for vanilla
             * @member
             * @type {string}
             */
            this["loaderVersion"] = "";
        }
        if (!("dir" in $$source)) {
            /**
             * folder name inside instances/; "" = legacy shared game dir
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * URL or base64
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * folder / category name
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * custom sort index
             * @member
             * @type {number | undefined}
             */
            this["sortOrder"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * in seconds
             * @member
             * @type {number | undefined}
             */
            this["playTime"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * in seconds (current day)
             * @member
             * @type {number | undefined}
             */
            this["playTimeToday"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "2006-01-02" of the last session
             * @member
             * @type {string | undefined}
             */
            this["lastPlayDay"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * unix timestamp
             * @member
             * @type {number | undefined}
             */
            this["lastPlayed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * optional direct connect address
             * @member
             * @type {string | undefined}
             */
            this["serverAddress"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Upstream modpack tracking (for auto-updates)
             * "modrinth" | "curseforge" | "ftb"
             * @member
             * @type {string | undefined}
             */
            this["modpackSource"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * project ID / slug
             * @member
             * @type {string | undefined}
             */
            this["modpackId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * installed version ID
             * @member
             * @type {string | undefined}
             */
            this["modpackVersionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * e.g. "1.0.0"
             * @member
             * @type {string | undefined}
             */
            this["modpackVersionName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Per-instance launch overrides; empty/zero = inherit global settings.
             * @member
             * @type {number | undefined}
             */
            this["ramMb"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["javaPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "" or "global" = inherit, aikar, zgc, shenandoah, default, none
             * @member
             * @type {string | undefined}
             */
            this["jvmPreset"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["jvmArgs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["useCustomWindow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["fullscreen"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["windowWidth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["windowHeight"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Instance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Instance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Instance(/** @type {Partial<Instance>} */($$parsedSource));
    }
}

/**
 * JavaRuntimeStatus describes the installation status of a major Java version.
 */
export class JavaRuntimeStatus {
    /**
     * Creates a new JavaRuntimeStatus instance.
     * @param {Partial<JavaRuntimeStatus>} [$$source = {}] - The source object to create the JavaRuntimeStatus.
     */
    constructor($$source = {}) {
        if (!("major" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["major"] = 0;
        }
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("managed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["managed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JavaRuntimeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JavaRuntimeStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JavaRuntimeStatus(/** @type {Partial<JavaRuntimeStatus>} */($$parsedSource));
    }
}

export class ModpackUpdateInfo {
    /**
     * Creates a new ModpackUpdateInfo instance.
     * @param {Partial<ModpackUpdateInfo>} [$$source = {}] - The source object to create the ModpackUpdateInfo.
     */
    constructor($$source = {}) {
        if (!("hasUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUpdate"] = false;
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("latestVersionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersionId"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("changelog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["changelog"] = "";
        }
        if (!("releaseDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModpackUpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModpackUpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModpackUpdateInfo(/** @type {Partial<ModpackUpdateInfo>} */($$parsedSource));
    }
}

/**
 * ScreenshotItem represents one screenshot taken in the instance.
 */
export class ScreenshotItem {
    /**
     * Creates a new ScreenshotItem instance.
     * @param {Partial<ScreenshotItem>} [$$source = {}] - The source object to create the ScreenshotItem.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modTime"] = 0;
        }
        if (!("dataUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenshotItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenshotItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenshotItem(/** @type {Partial<ScreenshotItem>} */($$parsedSource));
    }
}

/**
 * Settings is persisted to <root>/settings.json and bound to the frontend.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("ramMb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ramMb"] = 0;
        }
        if (!("resolution" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resolution"] = "";
        }
        if (!("javaPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["javaPath"] = "";
        }
        if (!("jvmPreset" in $$source)) {
            /**
             * aikar | zgc | shenandoah | default | none
             * @member
             * @type {string}
             */
            this["jvmPreset"] = "";
        }
        if (!("extraJvmArgs" in $$source)) {
            /**
             * user custom flags
             * @member
             * @type {string}
             */
            this["extraJvmArgs"] = "";
        }
        if (!("closeOnLaunch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["closeOnLaunch"] = false;
        }
        if (!("showSnapshots" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showSnapshots"] = false;
        }
        if (!("discordRpc" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["discordRpc"] = false;
        }
        if (!("discordAppId" in $$source)) {
            /**
             * Discord Developer Portal application id for Rich Presence
             * @member
             * @type {string}
             */
            this["discordAppId"] = "";
        }
        if (!("autoUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoUpdate"] = false;
        }
        if (!("launcherUpdates" in $$source)) {
            /**
             * self-update: check GitHub Releases on start
             * @member
             * @type {boolean}
             */
            this["launcherUpdates"] = false;
        }
        if (!("autoCleanCache" in $$source)) {
            /**
             * auto-delete cache older than 30 days on startup
             * @member
             * @type {boolean}
             */
            this["autoCleanCache"] = false;
        }
        if (!("selectedVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["selectedVersion"] = "";
        }
        if (!("activeInstance" in $$source)) {
            /**
             * id of the build ИГРАТЬ launches
             * @member
             * @type {string}
             */
            this["activeInstance"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * "ru" (default) or "en"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * custom folders / categories list
             * @member
             * @type {string[] | undefined}
             */
            this["groups"] = undefined;
        }
        if (!("centerWindow" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["centerWindow"] = false;
        }
        if (!("windowCustom" in $$source)) {
            /**
             * Window settings override
             * @member
             * @type {boolean}
             */
            this["windowCustom"] = false;
        }
        if (!("fullscreen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fullscreen"] = false;
        }
        if (!("windowWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField16_0($$parsedSource["groups"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * StatePayload is the bootstrap snapshot the UI loads on start.
 */
export class StatePayload {
    /**
     * Creates a new StatePayload instance.
     * @param {Partial<StatePayload>} [$$source = {}] - The source object to create the StatePayload.
     */
    constructor($$source = {}) {
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {Settings}
             */
            this["settings"] = (new Settings());
        }
        if (!("versions" in $$source)) {
            /**
             * @member
             * @type {VersionEntry[]}
             */
            this["versions"] = [];
        }
        if (!("latestRelease" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestRelease"] = "";
        }
        if (!("latestSnapshot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestSnapshot"] = "";
        }
        if (!("versionsErr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionsErr"] = "";
        }
        if (!("launcherVer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["launcherVer"] = "";
        }
        if (!("dataDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataDir"] = "";
        }
        if (!("accounts" in $$source)) {
            /**
             * @member
             * @type {auth$0.Account[]}
             */
            this["accounts"] = [];
        }
        if (!("activeId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeId"] = "";
        }
        if (!("instances" in $$source)) {
            /**
             * @member
             * @type {Instance[]}
             */
            this["instances"] = [];
        }
        if (!("activeInstance" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeInstance"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatePayload}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField9_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField1_0($$parsedSource["versions"]);
        }
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField7_0($$parsedSource["accounts"]);
        }
        if ("instances" in $$parsedSource) {
            $$parsedSource["instances"] = $$createField9_0($$parsedSource["instances"]);
        }
        return new StatePayload(/** @type {Partial<StatePayload>} */($$parsedSource));
    }
}

/**
 * UpdateInfo describes the result of an update check against GitHub Releases.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvailable"] = false;
        }
        if (!("releaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseUrl"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseNotes"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * VerifyResult reports the statistics of an instance verification scan.
 */
export class VerifyResult {
    /**
     * Creates a new VerifyResult instance.
     * @param {Partial<VerifyResult>} [$$source = {}] - The source object to create the VerifyResult.
     */
    constructor($$source = {}) {
        if (!("totalChecked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalChecked"] = 0;
        }
        if (!("repaired" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["repaired"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("details" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["details"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerifyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VerifyResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField3_0($$parsedSource["details"]);
        }
        return new VerifyResult(/** @type {Partial<VerifyResult>} */($$parsedSource));
    }
}

/**
 * VersionEntry is one row of the frontend version dropdown.
 */
export class VersionEntry {
    /**
     * Creates a new VersionEntry instance.
     * @param {Partial<VersionEntry>} [$$source = {}] - The source object to create the VersionEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionEntry(/** @type {Partial<VersionEntry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DetectedInstance.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Settings.createFrom;
const $$createType4 = VersionEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = auth$0.Account.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Instance.createFrom;
const $$createType9 = $Create.Array($$createType8);
