// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Account represents a user profile in the launcher.
 */
export class Account {
    /**
     * Creates a new Account instance.
     * @param {Partial<Account>} [$$source = {}] - The source object to create the Account.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {AccountType}
             */
            this["type"] = AccountType.$zero;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("uuid" in $$source)) {
            /**
             * Minecraft UUID
             * @member
             * @type {string}
             */
            this["uuid"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skinUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "classic" | "slim"
             * @member
             * @type {string | undefined}
             */
            this["skinModel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["capeUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MojangCape[] | undefined}
             */
            this["capes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["avatarUrl"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["createdAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("lastUsed" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["lastUsed"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (/** @type {any} */(false)) {
            /**
             * Microsoft specific fields
             * @member
             * @type {MSTokenData | null | undefined}
             */
            this["msToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MCTokenData | null | undefined}
             */
            this["mcToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["xuid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["ownsGame"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Account}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType1;
        const $$createField9_0 = $Create.DateFromTime;
        const $$createField10_0 = $Create.DateFromTime;
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capes" in $$parsedSource) {
            $$parsedSource["capes"] = $$createField7_0($$parsedSource["capes"]);
        }
        if ("createdAt" in $$parsedSource) {
            $$parsedSource["createdAt"] = $$createField9_0($$parsedSource["createdAt"]);
        }
        if ("lastUsed" in $$parsedSource) {
            $$parsedSource["lastUsed"] = $$createField10_0($$parsedSource["lastUsed"]);
        }
        if ("msToken" in $$parsedSource) {
            $$parsedSource["msToken"] = $$createField11_0($$parsedSource["msToken"]);
        }
        if ("mcToken" in $$parsedSource) {
            $$parsedSource["mcToken"] = $$createField12_0($$parsedSource["mcToken"]);
        }
        return new Account(/** @type {Partial<Account>} */($$parsedSource));
    }
}

/**
 * AccountType identifies whether an account is offline or authenticated via Microsoft.
 * @readonly
 * @enum {string}
 */
export const AccountType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AccountTypeOffline: "offline",
    AccountTypeMicrosoft: "microsoft",
};

/**
 * AccountsData represents the persisted accounts file payload.
 */
export class AccountsData {
    /**
     * Creates a new AccountsData instance.
     * @param {Partial<AccountsData>} [$$source = {}] - The source object to create the AccountsData.
     */
    constructor($$source = {}) {
        if (!("accounts" in $$source)) {
            /**
             * @member
             * @type {Account[]}
             */
            this["accounts"] = [];
        }
        if (!("activeId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountsData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountsData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField0_0($$parsedSource["accounts"]);
        }
        return new AccountsData(/** @type {Partial<AccountsData>} */($$parsedSource));
    }
}

/**
 * DeviceCodeResponse is returned by Microsoft OAuth device code endpoint.
 */
export class DeviceCodeResponse {
    /**
     * Creates a new DeviceCodeResponse instance.
     * @param {Partial<DeviceCodeResponse>} [$$source = {}] - The source object to create the DeviceCodeResponse.
     */
    constructor($$source = {}) {
        if (!("deviceCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceCode"] = "";
        }
        if (!("userCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userCode"] = "";
        }
        if (!("verificationUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verificationUri"] = "";
        }
        if (!("expiresIn" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expiresIn"] = 0;
        }
        if (!("interval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interval"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceCodeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceCodeResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceCodeResponse(/** @type {Partial<DeviceCodeResponse>} */($$parsedSource));
    }
}

/**
 * MCTokenData stores Minecraft Services access tokens.
 */
export class MCTokenData {
    /**
     * Creates a new MCTokenData instance.
     * @param {Partial<MCTokenData>} [$$source = {}] - The source object to create the MCTokenData.
     */
    constructor($$source = {}) {
        if (!("accessToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accessToken"] = "";
        }
        if (!("expiresAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["expiresAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCTokenData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MCTokenData}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expiresAt" in $$parsedSource) {
            $$parsedSource["expiresAt"] = $$createField1_0($$parsedSource["expiresAt"]);
        }
        return new MCTokenData(/** @type {Partial<MCTokenData>} */($$parsedSource));
    }
}

/**
 * MSTokenData stores Microsoft OAuth tokens.
 */
export class MSTokenData {
    /**
     * Creates a new MSTokenData instance.
     * @param {Partial<MSTokenData>} [$$source = {}] - The source object to create the MSTokenData.
     */
    constructor($$source = {}) {
        if (!("accessToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accessToken"] = "";
        }
        if (!("refreshToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refreshToken"] = "";
        }
        if (!("expiresAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["expiresAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MSTokenData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MSTokenData}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expiresAt" in $$parsedSource) {
            $$parsedSource["expiresAt"] = $$createField2_0($$parsedSource["expiresAt"]);
        }
        return new MSTokenData(/** @type {Partial<MSTokenData>} */($$parsedSource));
    }
}

/**
 * MojangCape represents a cape associated with a Minecraft profile.
 */
export class MojangCape {
    /**
     * Creates a new MojangCape instance.
     * @param {Partial<MojangCape>} [$$source = {}] - The source object to create the MojangCape.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * "ACTIVE" | "INACTIVE"
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dataUrl"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MojangCape instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MojangCape}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MojangCape(/** @type {Partial<MojangCape>} */($$parsedSource));
    }
}

/**
 * PresetCape represents a predefined popular cape.
 */
export class PresetCape {
    /**
     * Creates a new PresetCape instance.
     * @param {Partial<PresetCape>} [$$source = {}] - The source object to create the PresetCape.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dataUrl"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetCape instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetCape}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetCape(/** @type {Partial<PresetCape>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = MojangCape.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = MSTokenData.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = MCTokenData.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = Account.createFrom;
const $$createType7 = $Create.Array($$createType6);
