// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {launcher} from '../models';
import {main} from '../models';

export function AddOfflineAccount(arg1:string):Promise<auth.Account>;

export function CancelMicrosoftAuth():Promise<void>;

export function CancelPlay():Promise<void>;

export function CheckCurseForgeDependencies(arg1:string,arg2:string):Promise<Array<launcher.ResolvedDependency>>;

export function CheckInstanceModUpdates(arg1:string):Promise<Record<string, launcher.ContentItem>>;

export function CheckJavaUpdates():Promise<Array<launcher.JavaUpdateInfo>>;

export function CheckLauncherUpdate():Promise<main.UpdateInfo>;

export function CheckModDependencies(arg1:string,arg2:string):Promise<Array<launcher.ResolvedDependency>>;

export function ClearAccountCape(arg1:string):Promise<auth.Account>;

export function CloneInstance(arg1:string):Promise<main.Instance>;

export function CreateInstance(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Instance>;

export function DeleteInstance(arg1:string):Promise<string>;

export function DeleteInstanceContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteInstanceScreenshot(arg1:string,arg2:string):Promise<void>;

export function DeleteInstanceWorld(arg1:string,arg2:string):Promise<void>;

export function DeleteMod(arg1:string,arg2:string):Promise<void>;

export function DownloadLauncherUpdate():Promise<void>;

export function ExportInstance(arg1:string):Promise<string>;

export function FetchTextureBase64(arg1:string):Promise<string>;

export function GetAccounts():Promise<auth.AccountsData>;

export function GetArticle(arg1:string):Promise<launcher.ArticleDetails>;

export function GetInstalledMods(arg1:string):Promise<Array<launcher.ModItem>>;

export function GetInstanceAllContent(arg1:string):Promise<Array<launcher.ContentItem>>;

export function GetInstanceCrashReports(arg1:string):Promise<Array<main.CrashReport>>;

export function GetInstanceLogs(arg1:string):Promise<string>;

export function GetInstanceScreenshots(arg1:string):Promise<Array<main.ScreenshotItem>>;

export function GetInstanceWorlds(arg1:string):Promise<Array<launcher.WorldItem>>;

export function GetInstances():Promise<Array<main.Instance>>;

export function GetJavaRuntimesStatus():Promise<Array<main.JavaRuntimeStatus>>;

export function GetLauncherLogs():Promise<string>;

export function GetLoaderVersions(arg1:string,arg2:string):Promise<Array<launcher.LoaderVersionEntry>>;

export function GetModpackDetails(arg1:string,arg2:string):Promise<launcher.ModpackDetails>;

export function GetNews():Promise<Array<launcher.NewsEntry>>;

export function GetPresetCapes():Promise<Array<auth.PresetCape>>;

export function GetSettings():Promise<main.Settings>;

export function GetState():Promise<main.StatePayload>;

export function ImportInstanceDialog():Promise<main.Instance>;

export function ImportInstanceFile(arg1:string):Promise<main.Instance>;

export function InstallCurseForgeMod(arg1:string,arg2:string,arg3:string):Promise<launcher.ModItem>;

export function InstallCurseForgeModWithDependencies(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<launcher.ModItem>;

export function InstallJavaRuntime(arg1:number):Promise<void>;

export function InstallModWithDependencies(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<launcher.ModItem>;

export function InstallModpack(arg1:string,arg2:string,arg3:string):Promise<main.Instance>;

export function InstallModrinthMod(arg1:string,arg2:string,arg3:string):Promise<launcher.ModItem>;

export function OpenDataDir():Promise<void>;

export function OpenInstanceDir(arg1:string):Promise<void>;

export function OpenInstanceSubFolder(arg1:string,arg2:string):Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function OpenScreenshotsFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickCapeFile():Promise<main.FilePickResult>;

export function PickDataDir():Promise<string>;

export function PickInstanceIcon(arg1:string):Promise<string>;

export function PickJavaPath():Promise<string>;

export function PickSkinFile():Promise<main.FilePickResult>;

export function Play(arg1:string):Promise<void>;

export function PollMicrosoftAuth(arg1:string,arg2:number):Promise<auth.Account>;

export function RefreshAccount(arg1:string):Promise<auth.Account>;

export function RefreshVersions():Promise<main.StatePayload>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SearchCurseForgeMods(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<launcher.ModrinthSearchResponse>;

export function SearchModpacks(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<Array<launcher.ModpackItem>>;

export function SearchModrinthMods(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<launcher.ModrinthSearchResponse>;

export function SelectAccount(arg1:string):Promise<auth.Account>;

export function SetAccountCape(arg1:string,arg2:string,arg3:string):Promise<auth.Account>;

export function SetAccountSkin(arg1:string,arg2:string,arg3:string):Promise<auth.Account>;

export function SetActiveInstance(arg1:string):Promise<void>;

export function ShowFileInExplorer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartMicrosoftAuth():Promise<auth.DeviceCodeResponse>;

export function StopGame():Promise<void>;

export function ToggleInstanceContent(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ToggleMod(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function TranslateArticle(arg1:string,arg2:string):Promise<launcher.ArticleDetails>;

export function UninstallJavaRuntime(arg1:number):Promise<void>;

export function UpdateInstanceLaunchConfig(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:number,arg8:number):Promise<main.Instance>;

export function UpdateInstanceMod(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateInstanceSettings(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.Instance>;

export function WindowClose():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowToggleMaximize():Promise<boolean>;
