// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOfflineAccount(arg1) {
  return window['go']['main']['App']['AddOfflineAccount'](arg1);
}

export function CancelMicrosoftAuth() {
  return window['go']['main']['App']['CancelMicrosoftAuth']();
}

export function CancelPlay() {
  return window['go']['main']['App']['CancelPlay']();
}

export function CheckCurseForgeDependencies(arg1, arg2) {
  return window['go']['main']['App']['CheckCurseForgeDependencies'](arg1, arg2);
}

export function CheckInstanceModUpdates(arg1) {
  return window['go']['main']['App']['CheckInstanceModUpdates'](arg1);
}

export function CheckInstanceModpackUpdate(arg1) {
  return window['go']['main']['App']['CheckInstanceModpackUpdate'](arg1);
}

export function CheckJavaUpdates() {
  return window['go']['main']['App']['CheckJavaUpdates']();
}

export function CheckLauncherUpdate() {
  return window['go']['main']['App']['CheckLauncherUpdate']();
}

export function CheckModDependencies(arg1, arg2) {
  return window['go']['main']['App']['CheckModDependencies'](arg1, arg2);
}

export function ClearAccountCape(arg1) {
  return window['go']['main']['App']['ClearAccountCape'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function CloneInstance(arg1) {
  return window['go']['main']['App']['CloneInstance'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateInstance(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2, arg3, arg4);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DeleteInstanceContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteInstanceContent'](arg1, arg2, arg3);
}

export function DeleteInstanceScreenshot(arg1, arg2) {
  return window['go']['main']['App']['DeleteInstanceScreenshot'](arg1, arg2);
}

export function DeleteInstanceWorld(arg1, arg2) {
  return window['go']['main']['App']['DeleteInstanceWorld'](arg1, arg2);
}

export function DeleteMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteMod'](arg1, arg2);
}

export function DetectInstalledLaunchers() {
  return window['go']['main']['App']['DetectInstalledLaunchers']();
}

export function DownloadLauncherUpdate() {
  return window['go']['main']['App']['DownloadLauncherUpdate']();
}

export function ExportInstance(arg1) {
  return window['go']['main']['App']['ExportInstance'](arg1);
}

export function FetchTextureBase64(arg1) {
  return window['go']['main']['App']['FetchTextureBase64'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetArticle(arg1) {
  return window['go']['main']['App']['GetArticle'](arg1);
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetInstalledMods(arg1) {
  return window['go']['main']['App']['GetInstalledMods'](arg1);
}

export function GetInstanceAllContent(arg1) {
  return window['go']['main']['App']['GetInstanceAllContent'](arg1);
}

export function GetInstanceCrashReports(arg1) {
  return window['go']['main']['App']['GetInstanceCrashReports'](arg1);
}

export function GetInstanceLogs(arg1) {
  return window['go']['main']['App']['GetInstanceLogs'](arg1);
}

export function GetInstanceScreenshots(arg1) {
  return window['go']['main']['App']['GetInstanceScreenshots'](arg1);
}

export function GetInstanceWorlds(arg1) {
  return window['go']['main']['App']['GetInstanceWorlds'](arg1);
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetJavaRuntimesStatus() {
  return window['go']['main']['App']['GetJavaRuntimesStatus']();
}

export function GetLauncherLogs() {
  return window['go']['main']['App']['GetLauncherLogs']();
}

export function GetLoaderVersions(arg1, arg2) {
  return window['go']['main']['App']['GetLoaderVersions'](arg1, arg2);
}

export function GetModpackDetails(arg1, arg2) {
  return window['go']['main']['App']['GetModpackDetails'](arg1, arg2);
}

export function GetNews() {
  return window['go']['main']['App']['GetNews']();
}

export function GetPresetCapes() {
  return window['go']['main']['App']['GetPresetCapes']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportInstanceDialog() {
  return window['go']['main']['App']['ImportInstanceDialog']();
}

export function ImportInstanceFile(arg1) {
  return window['go']['main']['App']['ImportInstanceFile'](arg1);
}

export function ImportSelectedInstances(arg1) {
  return window['go']['main']['App']['ImportSelectedInstances'](arg1);
}

export function InstallCurseForgeMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallCurseForgeMod'](arg1, arg2, arg3);
}

export function InstallCurseForgeModWithDependencies(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallCurseForgeModWithDependencies'](arg1, arg2, arg3, arg4);
}

export function InstallJavaRuntime(arg1) {
  return window['go']['main']['App']['InstallJavaRuntime'](arg1);
}

export function InstallModWithDependencies(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallModWithDependencies'](arg1, arg2, arg3, arg4);
}

export function InstallModpack(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InstallModpack'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InstallModrinthMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallModrinthMod'](arg1, arg2, arg3);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenInstanceDir(arg1) {
  return window['go']['main']['App']['OpenInstanceDir'](arg1);
}

export function OpenInstanceSubFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenInstanceSubFolder'](arg1, arg2);
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function OpenScreenshotsFolder(arg1) {
  return window['go']['main']['App']['OpenScreenshotsFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickCapeFile() {
  return window['go']['main']['App']['PickCapeFile']();
}

export function PickDataDir() {
  return window['go']['main']['App']['PickDataDir']();
}

export function PickInstanceIcon(arg1) {
  return window['go']['main']['App']['PickInstanceIcon'](arg1);
}

export function PickJavaPath() {
  return window['go']['main']['App']['PickJavaPath']();
}

export function PickLauncherFolder() {
  return window['go']['main']['App']['PickLauncherFolder']();
}

export function PickSkinFile() {
  return window['go']['main']['App']['PickSkinFile']();
}

export function Play(arg1) {
  return window['go']['main']['App']['Play'](arg1);
}

export function PollMicrosoftAuth(arg1, arg2) {
  return window['go']['main']['App']['PollMicrosoftAuth'](arg1, arg2);
}

export function RefreshAccount(arg1) {
  return window['go']['main']['App']['RefreshAccount'](arg1);
}

export function RefreshVersions() {
  return window['go']['main']['App']['RefreshVersions']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function ReorderInstances(arg1) {
  return window['go']['main']['App']['ReorderInstances'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanCustomLauncherDir(arg1) {
  return window['go']['main']['App']['ScanCustomLauncherDir'](arg1);
}

export function SearchCurseForgeMods(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchCurseForgeMods'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchModpacks(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchModpacks'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchModrinthMods(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchModrinthMods'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectAccount(arg1) {
  return window['go']['main']['App']['SelectAccount'](arg1);
}

export function SetAccountCape(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAccountCape'](arg1, arg2, arg3);
}

export function SetAccountSkin(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAccountSkin'](arg1, arg2, arg3);
}

export function SetActiveInstance(arg1) {
  return window['go']['main']['App']['SetActiveInstance'](arg1);
}

export function ShowFileInExplorer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowFileInExplorer'](arg1, arg2, arg3);
}

export function StartMicrosoftAuth() {
  return window['go']['main']['App']['StartMicrosoftAuth']();
}

export function StopGame() {
  return window['go']['main']['App']['StopGame']();
}

export function ToggleInstanceContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ToggleInstanceContent'](arg1, arg2, arg3, arg4);
}

export function ToggleMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleMod'](arg1, arg2, arg3);
}

export function TranslateArticle(arg1, arg2) {
  return window['go']['main']['App']['TranslateArticle'](arg1, arg2);
}

export function UninstallJavaRuntime(arg1) {
  return window['go']['main']['App']['UninstallJavaRuntime'](arg1);
}

export function UpdateInstanceGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateInstanceGroup'](arg1, arg2);
}

export function UpdateInstanceLaunchConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateInstanceLaunchConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateInstanceMod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateInstanceMod'](arg1, arg2, arg3, arg4);
}

export function UpdateInstanceModpack(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateInstanceModpack'](arg1, arg2, arg3, arg4);
}

export function UpdateInstanceSettings(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateInstanceSettings'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function VerifyInstanceFiles(arg1) {
  return window['go']['main']['App']['VerifyInstanceFiles'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
